language: node_js
node_js:
  - "12"
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
  - cp CNAME .vuepress/dist/
  - cd .vuepress/dist
  - git init # Init temporary repo
  - git config user.email "trustq@qq.com" # Config Email
  - git config user.name "t532 via Travis CI" # Config Name
  - git add * # Stage
  - git commit -m "Travis CI Automated Deploy" # Commit
  - git remote add origin-gh-pages "https://$GITHUB_TOKEN@github.com/t532/t532.github.io.git" # Add Remote
  - git push --force --set-upstream origin-gh-pages master # Push
  - cd ../.. # Prevent Side-effects
