on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    - name: Build
      run: |
        npm install
        npm run build
    - name: Deploy to GitHub Pages
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cp CNAME .vuepress/dist/
        cd .vuepress/dist
        git init
        git config user.email "trustq@qq.com"
        git config user.name "Xy Ren via GitHub Actions"
        git add *
        git commit -m "GitHub Actions Automated Deploy"
        git remote add origin-gh-pages "https://$GH_TOKEN@github.com/xy-ren/xy-ren.github.io.git"
        git push --force --set-upstream origin-gh-pages master
